### ISSUE TITLE
Flow fails because of how metric gets called

### ISSUE THREAD

**Issue by aeberdinelli** [AndresSomadossi/ebased#4]
When implementing `processingFinished` method within the batchIterator for SQS, domain must return an object with a `body` property, otherwise it will fail. This happens because `outputMetric.responseReturned()` tries to use a detructuring of the domain response looking for a body. 

This should be optional since we don't always need to return something from the domain.

**Comment by AndresSomadossi** [comment]
Hi @aeberdinelli! 

Thanks for your comment.

I just fixed it in [#](https://github.com/AndresSomadossi/ebased/commit/9d6a6d72e810f0861a351cb06249052b4d0299df)

**Comment by AndresSomadossi** [comment]
Fix published in https://www.npmjs.com/package/ebased/v/1.2.2
